# Startship setup.

format = """
[╭─](bold black)$username@$hostname $directory $git_branch$git_status $cmd_duration
[╰─](bold black)$character
"""

[username]
show_always = true
format = "🐙[$user]($style) "

[directory]
style = "bold fg:#e5c07b"
truncation_length = 4
truncation_symbol = "…/"

[directory.substitutions]
"~" = ""

[git_branch]
symbol = " "
style = "bold fg:#98c379"

[git_status]
style = "fg:#e06c75"

[character]
success_symbol = "[❯](bold fg:#98c379)"
error_symbol = "[❯](bold fg:#e06c75)"

[docker_context]
symbol = " "
style = "bg:#06969A"
format = '[ $symbol $context ]($style)'

[python]
symbol = " "
format = "via [$symbol$version]($style) "
